version: '3.8'

services:
  db:
    image: postgres:14
    volumes:
      - creativeturtles_io_prod_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    networks:
      - backend

  web:
    build: .
    command: bundle exec puma -C config/puma.rb
    volumes:
      - .:/app
    depends_on:
      - db
    environment:
      RAILS_ENV: production
    networks:
      - backend

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt:/etc/letsencrypt
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - web
    networks:
      - backend

volumes:
  creativeturtles_io_prod_data:

networks:
  backend:
    driver: bridge
