version: '3.8'
services:
  db:
    image: postgres:14
    volumes:
      - creativeturtles_io_dev_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: creativeturtles_io_development
      POSTGRES_HOST_AUTH_METHOD: trust

  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: bundle exec rails s -b '0.0.0.0' -p 3000
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      RAILS_ENV: development
      DB_HOST: db
      HOST_NAME: "0.0.0.0:3000"
    stdin_open: true
    tty: true

  ws:
    image: anycable/anycable-go:1.5
    ports:
      - '8080:8080'
      - '8090:8090'
    environment:
      ANYCABLE_HOST: "0.0.0.0"
      ANYCABLE_BROADCAST_ADAPTER: http
      ANYCABLE_RPC_HOST: anycable:50051
      ANYCABLE_DEBUG: ${ANYCABLE_DEBUG:-true}

  anycable:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: bundle exec anycable
    volumes:
      - .:/app
    environment:
      RAILS_ENV: development
      DB_HOST: db
      ANYCABLE_RPC_HOST: 0.0.0.0:50051
      HOST_NAME: "0.0.0.0:3000"
    ports:
      - '50051:50051'
    depends_on:
      - db
      - ws

volumes:
  creativeturtles_io_dev_data:
