Video_Photography_Animation:
  - Assistant Director
  - 2D/3D Animator
  - Cinematographer
  - Film Director
  - Film Producer

Graphics_Design:
  - 3D Designer
  - Illustrator
  - Architect
  - Creative Director
  - Graphic Designer

Business:
  - Accountant
  - Project Manager
  - Business Consultant
  - Mechanical Engineer
  - HR Specialist

Programming_Tech:
  - AI Specialist
  - Software Developer
  - Systems Engineer
  - IT Consultant
  - GIS Specialist

Music_Audio:
  - Music Arranger
  - Music Producer
  - Audio Engineer
  - Musician
  - Conductor

Lifestyle:
  - Actor/Actress
  - Visual Artist
  - Chef
  - Florist
  - Health Educator

Digital_Marketing:
  - PPC Specialist
  - Content Creator
  - Digital Marketer
  - Marketing Consultant
  - Email Marketing Specialist

Writing_Translation:
  - Blogger
  - Editor
  - Copywriter
  - Content Writer
  - Co-Writer
